site_name: My Docs

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings
nav:
  - Overview: index.md

markdown_extensions:
  - mdx_math
  - admonition
  - sane_lists
  - pymdownx.highlight:
      auto_title: false
  - pymdownx.superfences
  - pymdownx.keys


